# Generated by Django 6.0.3 on 2026-03-30 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=15)),
                ("seat_number", models.CharField(max_length=10)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("Morning", "Morning"),
                            ("Evening", "Evening"),
                            ("Full Day", "Full Day"),
                        ],
                        max_length=20,
                    ),
                ),
                ("joining_date", models.DateField()),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=500, max_digits=8),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_on", models.DateField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
