# Generated by Django 6.0.3 on 2026-03-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="mode_of_payment",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Online", "Online")],
                default="Cash",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="contact",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="seat_number",
            field=models.CharField(max_length=2),
        ),
    ]
