# Generated by Django 6.0.3 on 2026-04-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_mode_of_payment_alter_student_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="seat_number",
            field=models.CharField(max_length=3),
        ),
    ]
