# Generated by Codex on 2026-05-05

from django.db import migrations, models


def backfill_payment_method_and_amount(apps, schema_editor):
    Payment = apps.get_model('students', 'Payment')

    for payment in Payment.objects.select_related('student').all():
        student = payment.student
        payment.payment_method = getattr(student, 'mode_of_payment', 'Cash') or 'Cash'
        if payment.is_paid and not payment.amount:
            payment.amount = student.monthly_fee
        payment.save(update_fields=['payment_method', 'amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(
                choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Online', 'Online')],
                default='Cash',
                max_length=10,
            ),
        ),
        migrations.RunPython(backfill_payment_method_and_amount, migrations.RunPython.noop),
    ]
