# Generated by Codex on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mode_of_payment',
            field=models.CharField(
                choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Online', 'Online')],
                default='Cash',
                max_length=10,
            ),
        ),
    ]
