# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='id_copy',
            field=models.FileField(blank=True, null=True, upload_to='student_profiles/id_copies/'),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_due_day',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='student',
            name='preparing_for',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='student_profiles/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(
                choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Left', 'Left')],
                default='Active',
                max_length=20,
            ),
        ),
    ]
