# Generated by Codex on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_portal_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('job_role', models.CharField(max_length=120)),
                ('current_work', models.CharField(blank=True, max_length=150)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('streams_known', models.TextField(help_text='Subjects, streams, or exams the mentor can handle')),
                ('bio', models.TextField(blank=True)),
                ('primary_session_mode', models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], default='Daily', max_length=20)),
                ('daily_session_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('monthly_session_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='mentor_profiles/photos/')),
                ('email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], default='Daily', max_length=20)),
                ('topic', models.CharField(max_length=180)),
                ('student_study_notes', models.TextField(blank=True)),
                ('preparation_target', models.CharField(blank=True, max_length=180)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mentor_questions', models.TextField(blank=True)),
                ('mentor_feedback', models.TextField(blank=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_sessions', to='students.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_sessions', to='students.student')),
            ],
        ),
    ]
