# Generated by Django 6.0.3 on 2026-05-09 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_mentorshipsession_scheduled_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="payment_qr",
            field=models.FileField(
                blank=True, null=True, upload_to="student_profiles/payment_qr/"
            ),
        ),
        migrations.CreateModel(
            name="PortalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_role",
                    models.CharField(
                        choices=[("Student", "Student"), ("Admin", "Admin")],
                        default="Student",
                        max_length=20,
                    ),
                ),
                ("sender_name", models.CharField(blank=True, max_length=100)),
                ("body", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="portal_messages/attachments/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_messages",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentOnlinePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("purpose", models.CharField(max_length=160)),
                ("months_covered", models.PositiveSmallIntegerField(default=0)),
                ("razorpay_order_id", models.CharField(max_length=80, unique=True)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=80)),
                ("razorpay_signature", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_payments",
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
